---
Name: apiroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    # 'signup': 'Signup'
    # 'signin': 'Signin'
    # 'member': 'Dashboard'
    # 'photosets/$sku': 'PhotoSetController'
    # 'cart': 'CartController'
    'api/v/1/pohto': 'PhotoAPI'
